version: '3.8'

services:

  db:
    image: postgres:15.2-alpine
    container_name: best_travel
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=best_travel
      - POSTGRES_USER=camilo
      - POSTGRES_PASSWORD=password123
    ports:
      - "5434:5432"

  cache-db:
    image: redis:6.2-alpine
    container_name: best_travel_cache
    restart: always
    ports:
      - "6381:6379"
    command: redis-server --loglevel warning --requirepass rediscam123lo