# context path
server:
  servlet:
    context-path: /best_travel

#spring configuraciones generales
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/best_travel
    username: camilo
    password: password123
    # pool de conexiones
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  # serializacion y deserializacion de XML
  jackson:
    serialization:
      INDENT_OUTPUT: true
    xml:
      enabled: true

# Configuración para Hibernate y niveles de log
logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE

